---
- name: start cndcdndummy
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-cnfcdndummy'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: cnfcdndummy
        template:
          metadata:
            labels:
              app: cnfcdndummy
          spec:
            containers:
            - name: cnfcdndummy
              image: "openshift/hello-openshift"
              ports:
                - containerPort: 8080

